import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import Loading from './(components)/Loading';

export const metadata: Metadata = {
  title: "ShareAway | ItsMe Prince",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
      </body>
    </html>
  );
}
